//
//  ASAPointEventType.swift
//  Date-O-Rama
//
//  Created by אהרן שלמה אדלמן on 10/01/2022.
//  Copyright © 2022 Adelsoft. All rights reserved.
//

import Foundation

enum ASAPointEventType: String, Codable {
    case generic = "gen"
    
    /// Event is when the center of the Sun is a specific number of degrees below the horizon
    case twilightRising  = "twiR"
    case twilightSetting = "twiS"
    
    /// Solar time, day lasts from sunrise to sunset
    case solarTimeSunriseSunset = "R2ST"
    
    /// Solar time, day lasts from dawn (sunrise - 72 minutes) to dusk (sunset + 72 minutes)
    case solarTimeDawn72MinutesDusk72Minutes = "D2DT"
    
    /// Fajr Islamic prayer time
    case fajrJafari                 = "FajrJafari"
    case fajrJafariMidnight         = "FajrJafariMidnight"
    case fajrJafariOneSeventh       = "FajrJafari1/7"
    case fajrJafariAngleBased       = "FajrJafariAngleBased"
    case fajrKarachi                = "FajrKarachi"
    case fajrKarachiMidnight        = "FajrKarachiMidnight"
    case fajrKarachiOneSeventh      = "FajrKarachi1/7"
    case fajrKarachiAngleBased      = "FajrKarachiAngleBased"
    case fajrISNA                   = "FajrISNA"
    case fajrISNAMidnight           = "FajrISNAMidnight"
    case fajrISNAOneSeventh         = "FajrISNA1/7"
    case fajrISNAAngleBased         = "FajrISNAAngleBased"
    case fajrMWL                    = "FajrMWL"
    case fajrMWLMidnight            = "FajrMWLMidnight"
    case fajrMWLOneSeventh          = "FajrMWL1/7"
    case fajrMWLAngleBased          = "FajrMWLAngleBased"
    case fajrMakkah                 = "FajrMakkah"
    case fajrMakkahMidnight         = "FajrMakkahMidnight"
    case fajrMakkahOneSeventh       = "FajrMakkah1/7"
    case fajrMakkahAngleBased       = "FajrMakkahAngleBased"
    case fajrEgypt                  = "FajrEgypt"
    case fajrEgyptMidnight          = "FajrEgyptMidnight"
    case fajrEgyptOneSeventh        = "FajrEgypt1/7"
    case fajrEgyptAngleBased        = "FajrEgyptAngleBased"
    case fajrTehran                 = "FajrTehran"
    case fajrTehranMidnight         = "FajrTehranMidnight"
    case fajrTehranOneSeventh       = "FajrTehran1/7"
    case fajrTehranAngleBased       = "FajrTehranAngleBased"
    /// Dhuhr Islamic prayer time
    case dhuhrJafari                = "DhuhrJafari"
    case dhuhrJafariMidnight        = "DhuhrJafariMidnight"
    case dhuhrJafariOneSeventh      = "DhuhrJafari1/7"
    case dhuhrJafariAngleBased      = "DhuhrJafariAngleBased"
    case dhuhrKarachi               = "DhuhrKarachi"
    case dhuhrKarachiMidnight       = "DhuhrKarachiMidnight"
    case dhuhrKarachiOneSeventh     = "DhuhrKarachi1/7"
    case dhuhrKarachiAngleBased     = "DhuhrKarachiAngleBased"
    case dhuhrISNA                  = "DhuhrISNA"
    case dhuhrISNAMidnight          = "DhuhrISNAMidnight"
    case dhuhrISNAOneSeventh        = "DhuhrISNA1/7"
    case dhuhrISNAAngleBased        = "DhuhrISNAAngleBased"
    case dhuhrMWL                   = "DhuhrMWL"
    case dhuhrMWLMidnight           = "DhuhrMWLMidnight"
    case dhuhrMWLOneSeventh         = "DhuhrMWL1/7"
    case dhuhrMWLAngleBased         = "DhuhrMWLAngleBased"
    case dhuhrMakkah                = "DhuhrMakkah"
    case dhuhrMakkahMidnight        = "DhuhrMakkahMidnight"
    case dhuhrMakkahOneSeventh      = "DhuhrMakkah1/7"
    case dhuhrMakkahAngleBased      = "DhuhrMakkahAngleBased"
    case dhuhrEgypt                 = "DhuhrEgypt"
    case dhuhrEgyptMidnight         = "DhuhrEgyptMidnight"
    case dhuhrEgyptOneSeventh       = "DhuhrEgypt1/7"
    case dhuhrEgyptAngleBased       = "DhuhrEgyptAngleBased"
    case dhuhrTehran                = "DhuhrTehran"
    case dhuhrTehranMidnight        = "DhuhrTehranMidnight"
    case dhuhrTehranOneSeventh      = "DhuhrTehran1/7"
    case dhuhrTehranAngleBased      = "DhuhrTehranAngleBased"
    /// Asr Islamic prayer time
    case asrShafiiJafari            = "AsrShafiiJafari"
    case asrShafiiJafariMidnight    = "AsrShafiiJafariMidnight"
    case asrShafiiJafariOneSeventh  = "AsrShafiiJafari1/7"
    case asrShafiiJafariAngleBased  = "AsrShafiiJafariAngleBased"
    case asrHanafiJafari            = "AsrHanafiJafari"
    case asrHanafiJafariMidnight    = "AsrHanafiJafariMidnight"
    case asrHanafiJafariOneSeventh  = "AsrHanafiJafari1/7"
    case asrHanafiJafariAngleBased  = "AsrHanafiJafariAngleBased"
    case asrShafiiKarachi           = "AsrShafiiKarachi"
    case asrShafiiKarachiMidnight   = "AsrShafiiKarachiMidnight"
    case asrShafiiKarachiOneSeventh = "AsrShafiiKarachi1/7"
    case asrShafiiKarachiAngleBased = "AsrShafiiKarachiAngleBased"
    case asrHanafiKarachi           = "AsrHanafiKarachi"
    case asrHanafiKarachiMidnight   = "AsrHanafiKarachiMidnight"
    case asrHanafiKarachiOneSeventh = "AsrHanafiKarachi1/7"
    case asrHanafiKarachiAngleBased = "AsrHanafiKarachiAngleBased"
    case asrShafiiISNA              = "AsrShafiiISNA"
    case asrShafiiISNAMidnight      = "AsrShafiiISNAMidnight"
    case asrShafiiISNAOneSeventh    = "AsrShafiiISNA1/7"
    case asrShafiiISNAAngleBased    = "AsrShafiiISNAAngleBased"
    case asrHanafiISNA              = "AsrHanafiISNA"
    case asrHanafiISNAMidnight      = "AsrHanafiISNAMidnight"
    case asrHanafiISNAOneSeventh    = "AsrHanafiISNA1/7"
    case asrHanafiISNAAngleBased    = "AsrHanafiISNAAngleBased"
    case asrShafiiMWL               = "AsrShafiiMWL"
    case asrShafiiMWLMidnight       = "AsrShafiiMWLMidnight"
    case asrShafiiMWLOneSeventh     = "AsrShafiiMWL1/7"
    case asrShafiiMWLAngleBased     = "AsrShafiiMWLAngleBased"
    case asrHanafiMWL               = "AsrHanafiMWL"
    case asrHanafiMWLMidnight       = "AsrHanafiMWLMidnight"
    case asrHanafiMWLOneSeventh     = "AsrHanafiMWL1/7"
    case asrHanafiMWLAngleBased     = "AsrHanafiMWLAngleBased"
    case asrShafiiMakkah            = "AsrShafiiMakkah"
    case asrShafiiMakkahMidnight    = "AsrShafiiMakkahMidnight"
    case asrShafiiMakkahOneSeventh  = "AsrShafiiMakkah1/7"
    case asrShafiiMakkahAngleBased  = "AsrShafiiMakkahAngleBased"
    case asrHanafiMakkah            = "AsrHanafiMakkah"
    case asrHanafiMakkahMidnight    = "AsrHanafiMakkahMidnight"
    case asrHanafiMakkahOneSeventh  = "AsrHanafiMakkah1/7"
    case asrHanafiMakkahAngleBased  = "AsrHanafiMakkahAngleBased"
    case asrShafiiEgypt             = "AsrShafiiEgypt"
    case asrShafiiEgyptMidnight     = "AsrShafiiEgyptMidnight"
    case asrShafiiEgyptOneSeventh   = "AsrShafiiEgypt1/7"
    case asrShafiiEgyptAngleBased   = "AsrShafiiEgyptAngleBased"
    case asrHanafiEgypt             = "AsrHanafiEgypt"
    case asrHanafiEgyptMidnight     = "AsrHanafiEgyptMidnight"
    case asrHanafiEgyptOneSeventh   = "AsrHanafiEgypt1/7"
    case asrHanafiEgyptAngleBased   = "AsrHanafiEgyptAngleBased"
    case asrShafiiTehran            = "AsrShafiiTehran"
    case asrShafiiTehranMidnight    = "AsrShafiiTehranMidnight"
    case asrShafiiTehranOneSeventh  = "AsrShafiiTehran1/7"
    case asrShafiiTehranAngleBased  = "AsrShafiiTehranAngleBased"
    case asrHanafiTehran            = "AsrHanafiTehran"
    case asrHanafiTehranMidnight    = "AsrHanafiTehranMidnight"
    case asrHanafiTehranOneSeventh  = "AsrHanafiTehran1/7"
    case asrHanafiTehranAngleBased  = "AsrHanafiTehranAngleBased"
    /// Maghrib Islamic prayer time
    case maghribJafari              = "MaghribJafari"
    case maghribJafariMidnight      = "MaghribJafariMidnight"
    case maghribJafariOneSeventh    = "MaghribJafari1/7"
    case maghribJafariAngleBased    = "MaghribJafariAngleBased"
    case maghribKarachi             = "MaghribKarachi"
    case maghribKarachiMidnight     = "MaghribKarachiMidnight"
    case maghribKarachiOneSeventh   = "MaghribKarachi1/7"
    case maghribKarachiAngleBased   = "MaghribKarachiAngleBased"
    case maghribISNA                = "MaghribISNA"
    case maghribISNAMidnight        = "MaghribISNAMidnight"
    case maghribISNAOneSeventh      = "MaghribISNA1/7"
    case maghribISNAAngleBased      = "MaghribISNAAngleBased"
    case maghribMWL                 = "MaghribMWL"
    case maghribMWLMidnight         = "MaghribMWLMidnight"
    case maghribMWLOneSeventh       = "MaghribMWL1/7"
    case maghribMWLAngleBased       = "MaghribMWLAngleBased"
    case maghribMakkah              = "MaghribMakkah"
    case maghribMakkahMidnight      = "MaghribMakkahMidnight"
    case maghribMakkahOneSeventh    = "MaghribMakkah1/7"
    case maghribMakkahAngleBased    = "MaghribMakkahAngleBased"
    case maghribEgypt               = "MaghribEgypt"
    case maghribEgyptMidnight       = "MaghribEgyptMidnight"
    case maghribEgyptOneSeventh     = "MaghribEgypt1/7"
    case maghribEgyptAngleBased     = "MaghribEgyptAngleBased"
    case maghribTehran              = "MaghribTehran"
    case maghribTehranMidnight      = "MaghribTehranMidnight"
    case maghribTehranOneSeventh    = "MaghribTehran1/7"
    case maghribTehranAngleBased    = "MaghribTehranAngleBased"
    /// Isha Islamic prayer time
    case ishaJafari                 = "IshaJafari"
    case ishaJafariMidnight         = "IshaJafariMidnight"
    case ishaJafariOneSeventh       = "IshaJafari1/7"
    case ishaJafariAngleBased       = "IshaJafariAngleBased"
    case ishaKarachi                = "IshaKarachi"
    case ishaKarachiMidnight        = "IshaKarachiMidnight"
    case ishaKarachiOneSeventh      = "IshaKarachi1/7"
    case ishaKarachiAngleBased      = "IshaKarachiAngleBased"
    case ishaISNA                   = "IshaISNA"
    case ishaISNAMidnight           = "IshaISNAMidnight"
    case ishaISNAOneSeventh         = "IshaISNA1/7"
    case ishaISNAAngleBased         = "IshaISNAAngleBased"
    case ishaMWL                    = "IshaMWL"
    case ishaMWLMidnight            = "IshaMWLMidnight"
    case ishaMWLOneSeventh          = "IshaMWL1/7"
    case ishaMWLAngleBased          = "IshaMWLAngleBased"
    case ishaMakkah                 = "IshaMakkah"
    case ishaMakkahMidnight         = "IshaMakkahMidnight"
    case ishaMakkahOneSeventh       = "IshaMakkah1/7"
    case ishaMakkahAngleBased       = "IshaMakkahAngleBased"
    case ishaEgypt                  = "IshaEgypt"
    case ishaEgyptMidnight          = "IshaEgyptMidnight"
    case ishaEgyptOneSeventh        = "IshaEgypt1/7"
    case ishaEgyptAngleBased        = "IshaEgyptAngleBased"
    case ishaTehran                 = "IshaTehran"
    case ishaTehranMidnight         = "IshaTehranMidnight"
    case ishaTehranOneSeventh       = "IshaTehran1/7"
    case ishaTehranAngleBased       = "IshaTehranAngleBased"

    /// Rise of the Moon or a planet
    case rise = "rise"
    
    /// Rise of the Moon or a planet
    case set  = "set"
} // enum ASAPointEventType
